#!/bin/bash -l

#SBATCH --ntasks 32
#SBATCH --mem=250G
#SBATCH -J tangos-crosslink
#SBATCH -o ./logs/crosslink.out
#SBATCH -e ./logs/crosslink.err
#SBATCH -p CORES64
#SBATCH -t 2880 # minutes run time
#SBATCH --exclusive

##########################################################
# Select database

# tangos_mysql is an alias for setting the TANGOS_DB_CONNECTION environment variable
tangos_mysql eagle

##########################################################

export TANGOS_TYPE='halo'
export TANGOS_EXTRAS='' # add --force to recompute

##########################################################

# export LINK1="EAGLE_GM_halo_049_RECAL_z2_od_1p000_SEED42"
# export LINK1="EAGLE_GM_halo_049_RECAL_z2_od_1p300_SEED42"
# export LINK1="EAGLE_GM_halo_049_DMONLY_z2_od_1p000_SEED42"
# export LINK1="EAGLE_GM_halo_049_DMONLY_z2_od_1p300_SEED42"
export LINK1="EAGLE_GM_halo_049_hires_RECAL_z2_od_1p000_SEED42"
# export LINK1="EAGLE_GM_halo_049_hires_DMONLY_z2_od_1p000_SEED42"

##########################################################

# sim="halo_049"
sim="halo_049_hires"
# sim="halo_013"
model="RECAL"
# model="NOAGNFB"
# model="DMONLY"
# model="ONLYAGN"

# declare -a ics=("z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000_merger_z1p7_1p100")
# declare -a ics=("z2_od_1p300" "z2_od_1p050")
# declare -a ics=("z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000_merger_z1p7_1p100")
# declare -a ics=("z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000" "z2_od_1p000_merger_z1p7_1p100")
# declare -a ics=("var_0p850_filt4" "var_0p950_filt4_merger_0p800")

# declare -a ics=("var_0p950_filt4" "var_0p950_filt3")
# declare -a ics=("var_0p950_filt2p5" "var_0p950_filt2p7" "var_0p900_filt2p5" "var_0p900_filt2p7")
# declare -a ics=("z2_10prog_1p050" "z2_10prog_1p100")

# declare -a ics=("z2_od_1p000_merger_z1p7_1p125" "z2_od_1p000_merger_z1p7_1p150" "z2_od_1p000_merger_z1p7_1p200")
# declare -a ics=("z2_od_1p300_merger_z1p7_1p200" "z2_od_1p300_merger_z1p7_1p400")

# declare -a ics=("z2_od_1p300_z3_progs_1p400_hc" "z2_od_1p000_merger_z1p7_1p125_hc")
declare -a ics=("z2_od_1p000_merger_z1p7_0p800_hc" "z2_od_1p300_hc")


tolink=${ics[$SLURM_ARRAY_TASK_ID]}

# tolink="z2_od_1p000"
# tolink="z2_od_1p300"
# tolink="z2_od_1p000_merger_z1p7_0p800"
# tolink="z2_od_1p000_merger_z1p7_1p125"
# tolink="z2_od_1p000_merger_z1p7_1p150"
# tolink="z2_od_1p300_z3_progs_1p400"

##########################################################
# Seeds

declare -a seeds=("SEED42" "SEED01" "SEED02" "SEED03" "SEED04" "SEED05" "SEED06" "SEED07" "SEED08")

seed="SEED42"
# seed=${seeds[$SLURM_ARRAY_TASK_ID]}


##########################################################


export LINK2="EAGLE_GM_${sim}_${model}_${tolink}_${seed}"

echo $LINK1
echo $LINK2

# tangos crosslink $LINK1 $LINK2 --type=$TANGOS_TYPE $TANGOS_EXTRAS

mpirun -np $SLURM_NTASKS tangos crosslink $LINK1 $LINK2 --backend mpi4py
