#!/bin/bash -l

#SBATCH --ntasks 32
#SBATCH --mem=500G
#SBATCH -J tangos
#SBATCH -o ./logs/tangos.out
#SBATCH -e ./logs/tangos.log
#SBATCH -p CORES64
#SBATCH -t 2880 # minutes run time
#SBATCH --exclusive

##########################################################
# Select database

# tangos_mysql is an alias for setting the TANGOS_DB_CONNECTION environment variable
tangos_mysql eagle

##########################################################

# sim="halo_049"
sim="halo_049_hires"

model="RECAL"
# model="DMONLY"
# model="NOAGN"
# model="ONLYAGN"
# model="NOAGNFB"

export TANGOS_MAX_OBJECTS=20

export TANGOS_TYPE='halo'

export TANGOS_EXTRAS='--force --verbose' # add --force to recompute
# export TANGOS_EXTRAS='--verbose' # add --force to recompute

##########################################################
# ICs

# declare -a ics=("z2_od_1p000" "z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000_merger_z1p7_1p100")
# declare -a ics=("var_0p850_filt4" "var_0p950_filt4_merger_0p800")
# declare -a ics=("z2_od_1p000" "z2_od_1p300" "z2_od_1p050")
# declare -a ics=("var_0p950_filt2p5" "var_0p950_filt2p7" "var_0p900_filt2p5" "var_0p900_filt2p7")
# declare -a ics=("z2_10prog_1p050" "z2_10prog_1p100")

# declare -a ics=("z2_od_1p000" "z2_od_1p050" "z2_od_1p300" "z2_od_1p300_z3_haloes234_1p400" "z2_od_1p300_z3_haloes234_1p500")
# declare -a ics=("z2_od_1p000_merger_z1p7_1p125" "z2_od_1p000_merger_z1p7_1p150" "z2_od_1p000_merger_z1p7_1p200")

# declare -a ics=("z2_od_1p000" "z2_od_1p300" "z2_od_1p300_z3_progs_1p400" "z2_od_1p000_merger_z1p7_0p800")

# declare -a ics=("z2_od_1p300_z3_progs_1p400_hc" "z2_od_1p000_merger_z1p7_1p125_hc")
declare -a ics=("z2_od_1p000_merger_z1p7_0p800_hc" "z2_od_1p300_hc")

# ic="z2_od_1p000_merger_z1p7_1p150"
# ic="z2_od_1p000_merger_z1p7_1p125"
# ic="z2_od_1p000_merger_z1p7_0p800"
# ic="z2_od_1p000"
# ic="z2_od_1p300"
# ic="z2_od_1p300_z3_progs_1p400"
# ic="z2_od_1p300_z3_progs_1p400_hc"
ic="z2_od_1p000_merger_z1p7_1p125_hc"
# ic=${ics[$SLURM_ARRAY_TASK_ID]}

##########################################################
# Seeds

declare -a seeds=("SEED42" "SEED01" "SEED02" "SEED03" "SEED04" "SEED05" "SEED06" "SEED07" "SEED08")

seed="SEED01"
# seed=${seeds[$SLURM_ARRAY_TASK_ID]}

##########################################################
# Build path

export TANGOS_SIM="EAGLE/GM/${sim}/${model}/${ic}/${seed}"

##########################################################
# Adding simulation to database

mpirun -np $SLURM_NTASKS python ../tangos_eagle/assign_subgroupnumbers_mpi.py $TANGOS_SIM

tangos add $TANGOS_SIM --max-objects $TANGOS_MAX_OBJECTS

tangos import-properties --for $TANGOS_SIM

mpirun -np $SLURM_NTASKS tangos link --for $TANGOS_SIM --backend mpi4py

##########################################################
# Compute properties
#
mpirun -np $SLURM_NTASKS tangos write r200 --with-prerequisites --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

mpirun -np $SLURM_NTASKS tangos write M200 --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

mpirun -np $SLURM_NTASKS tangos write finder_mass --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

mpirun -np $SLURM_NTASKS tangos write subfind_centre_potential --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
# mpirun -np $SLURM_NTASKS tangos write binding_zeropoint --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
# mpirun -np $SLURM_NTASKS tangos write E_bind_200 --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
# mpirun -np $SLURM_NTASKS tangos write E_bind_200_particle --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
# mpirun -np $SLURM_NTASKS tangos write E_bind_2500_particle --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS


if [[ ${model} == "RECAL" ]] || [[ ${model} == "NOAGN" ]] || [[ ${model} == "NOAGNFB" ]] || [[ ${model} == "ONLYAGN" ]]; then

  mpirun -np $SLURM_NTASKS tangos write finder_star_mass --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write f_CGM --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write Mstar_30kpc --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write E_SN --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write Mgas_30kpc_sf --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write kappa_co --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  mpirun -np $SLURM_NTASKS tangos write gas_rhalf_kappa --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  # mpirun -np $SLURM_NTASKS tangos write CGM_kappa_co --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  if [[ ${model} == "RECAL" ]] || [[ ${model} == "ONLYAGN" ]] || [[ ${model} == "NOAGNFB" ]]; then

    mpirun -np $SLURM_NTASKS tangos write M_BH --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
    mpirun -np $SLURM_NTASKS tangos write bound_central_M_BH --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

    mpirun -np $SLURM_NTASKS tangos write BH_Density --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS
    mpirun -np $SLURM_NTASKS tangos write BH_kpc_ap_mass --type=$TANGOS_TYPE --for $TANGOS_SIM --backend mpi4py $TANGOS_EXTRAS

  fi

fi


##########################################################
# Cleanup

tangos remove-duplicates
