#!/bin/bash -l

#SBATCH --ntasks 1
#SBATCH -J tangos
#SBATCH -o ./logs/tangos.out
#SBATCH -e ./logs/tangos.err
#SBATCH -p SMP
#SBATCH -t 2880 # minutes run time

##########################################################

sim="halo_049"
model="NOAGN"

export TANGOS_TYPE='halo'

export TANGOS_EXTRAS='--force --verbose' # add --force to recompute


##########################################################
# ICs

# declare -a ics=("z2_od_0p950" "z2_od_0p975" "z2_od_0p988" "z2_od_1p000" "z2_od_1p013" "z2_od_1p025" "z2_od_1p050")
declare -a ics=("z2_od_0p950" "z2_od_1p000" "z2_od_1p050")
# declare -a ics=("z2_od_0p950" "z2_od_1p050")

ic="z2_od_1p000"
# ic=${ics[$SLURM_ARRAY_TASK_ID]}

##########################################################
# Seeds

declare -a seeds=("SEED42" "SEED01" "SEED02" "SEED03" "SEED04" "SEED05" "SEED06" "SEED07" "SEED08" "SEED09")

seed="SEED02"
# seed=${seeds[$SLURM_ARRAY_TASK_ID]}

##########################################################


# export TANGOS_SIM="liverpool/EAGLE/GM/${sim}/${model}/${ic}/${seed}"
export TANGOS_SIM="EAGLE/GM/${sim}/${model}/${ic}/${seed}"

echo $SLURM_NTASKS


tangos write f_ex_situ --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

tangos write kappa_co --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write r200 --with-prerequisites --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write M200 --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write finder_mass --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write f_CGM --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write M_BH --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write Mstar_30kpc --with-prerequisites --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

# tangos write f_star_hot --type=$TANGOS_TYPE --for $TANGOS_SIM $TANGOS_EXTRAS

tangos remove-duplicates