#!/bin/bash -l

#SBATCH --ntasks 24
#SBATCH -J tangos-crosslink
#SBATCH -o ./logs/crosslink.out
#SBATCH -e ./logs/crosslink.err
#SBATCH -p CORES24
#SBATCH -t 2880 # minutes run time

##########################################################

# tangos_mysql is an alias for setting the TANGOS_DB_CONNECTION environment variable
tangos_mysql eagle

sim="halo_049_hires"
model1="DMONLY"
model2="DMONLY"
seed1="SEED42"
seed2="SEED42"

export TANGOS_TYPE='halo'
export TANGOS_EXTRAS='--force' # add --force to recompute

##########################################################

linkwith="z2_od_1p000"

# declare -a arr=("z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000_merger_z1p7_0p900" "z2_od_1p000_merger_z1p7_1p100" "z2_od_1p000_merger_z1p7_1p200")
declare -a arr=("z2_od_1p000_merger_z1p7_0p800" "z2_od_1p000_merger_z1p7_1p100")

# tolink=${arr[$SLURM_ARRAY_TASK_ID]}

tolink="z2_od_1p300"

##########################################################

export LINK1="EAGLE_GM_${sim}_${model1}_${linkwith}_${seed1}"
export LINK2="EAGLE_GM_${sim}_${model2}_${tolink}_${seed2}"

echo $LINK1
echo $LINK2

mpirun -np $SLURM_NTASKS tangos crosslink $LINK1 $LINK2 --type=$TANGOS_TYPE --backend mpi4py $TANGOS_EXTRAS
