#!/bin/bash -l

#SBATCH --ntasks 20
#SBATCH -J tangos
#SBATCH -o ./logs/tangos.out
#SBATCH -e ./logs/tangos.err
#SBATCH -p SMP
#SBATCH -t 2880 # minutes run time

##########################################################

sim="halo_049"
model="RECAL"
seed="SEED42"

export TANGOS_MAX_OBJECTS=20

##########################################################

declare -a arr=("z2_od_0p950" "z2_od_0p975" "z2_od_0p988" "z2_od_1p000" "z2_od_1p013" "z2_od_1p025" "z2_od_1p050")

gm=${arr[$SLURM_ARRAY_TASK_ID]}

export TANGOS_SIM="liverpool/EAGLE/GM/${sim}/${model}/${gm}/${seed}"


python ../tangos_eagle/assign_subgroupnumbers.py $TANGOS_SIM

tangos add $TANGOS_SIM --max-objects $TANGOS_MAX_OBJECTS

tangos import-properties --type group --for $TANGOS_SIM
tangos import-properties --for $TANGOS_SIM

mpirun -np $SLURM_NTASKS tangos link --for $TANGOS_SIM --backend mpi4py
mpirun -np $SLURM_NTASKS tangos link --type group --for $TANGOS_SIM --backend mpi4py


